### ISSUE TITLE
Android app asks for too much permissions during installation

### ISSUE THREAD

**Issue by santiment-admin** [santiment/SantimentMobile#55]

**Comment by santiment-admin** [comment]
https://github.com/facebook/react-native/issues/5886

**Comment by santiment-admin** [comment]
https://github.com/facebook/react-native/issues/5886#issuecomment-264838372

Implement the solution from the comment above.

Verify that persistence and remote debugging works after that.

**Comment by igormatyushkin014** [comment]
@santiment-admin Done.
