### ISSUE TITLE
The last item in the list is't  correctly displayed 

### ISSUE THREAD

**Issue by OceanBloodd** [santiment/SantimentMobile#7]
Nexus 5/android 6.0.1
Santiment 0.2.2

1. Run app
2. Tap on ETH_USD button
3. Scroll down the list 
AR: The last item in the list isn't  displayed correctly

![screenshot_20170405-173823](https://cloud.githubusercontent.com/assets/26921216/24711142/c506f21c-1a27-11e7-8013-f619b4b1abb2.png)

**Comment by santiment-admin** [comment]
Fixed on MySentiment screen. Do the same for AddCurrency screen.
