### ISSUE TITLE
Refactor styles and colors

### ISSUE THREAD

**Issue by etartakovsky** [santiment/SantimentMobile#72]
These guides describe approximately the approach we should use: 
https://medium.com/@tommylackemann/managing-styles-in-react-native-3546d3482d73
https://medium.com/the-react-native-log/tips-for-styling-your-react-native-apps-3f61608655eb

`style.js` file for each component
`resources/colors.js` file with reusable colors
`resources/fonts.js` file with reusable fonts

Neither fonts nor colors should be hardcoded.

**Comment by igormatyushkin014** [comment]
@etartakovsky Done.
