### ISSUE TITLE
Landscape orientation. List disappears  

### ISSUE THREAD

**Issue by OceanBloodd** [santiment/SantimentMobile#8]
Nexus 5/android 6.0.1
Iphone 5s/ios 10.3.1
Santiment 0.2.2

1. Open App
2. Tap on btc/use or eth/usd
3. Turn the phone in landscape orientation
AR: The list below the schedule disappears 
ER: the list will be under the chart

[Video](https://www.dropbox.com/s/iw0lvgduresao6m/%D0%BE%D1%80%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F.mp4?dl=0)

**Comment by santiment-admin** [comment]
Landscape orientation is not supported. Disabled. a05c163
